#!/usr/bin/env python

# Script:  mu2Psi.py
# Purpose: This script reads a file containing a dipole projection profile
#          and calculates the corresponding electrostatic potential (Psi).
# Syntax:  mu2Psi.py inputFile area
#          inputFile = LAMMPS output file generated by fix ave/spatial
#          area = surface area of slabs in Angstrom^2
# Example: ./mu2Psi.py qDensPhos.profile 4630 > elPotDip.dat 
# Author:  Mario Orsi (orsimario at gmail.com)

import sys,os,string

if len(sys.argv) != 3:
  print "Syntax: mu2Psi.py inputFile area"
  sys.exit()

inFileName = sys.argv[1]
area = float(sys.argv[2])
inFile = open(inFileName, "r")
lines = inFile.readlines()
inFile.close()

eps0 = 8.854e-12 # [C/(Vm)] permittivity of free space
e_in_C = 1.6021766e-19 # magnitude of electron charge in Coulomb
A_in_m = 1e-10 # angstrom in meter
cFac = e_in_C / ( A_in_m * A_in_m ) # conversion factor for LAMMPS units 

# find bin thickness (delta):
for line in lines:
    if line[0] != '#': # ignore comments
        words = string.split(line)
        if len(words) == 2:
            nBins = int(words[1])
        if len(words) == 4:
            if int(words[0]) == 1:
                coordLower = float(words[1])
            if int(words[0]) == nBins:
                coordUpper = float(words[1])
delta = abs( coordUpper - coordLower ) / ( nBins - 1 )

slabVolume = area * delta

# calculate and output electric field:
muProjInt = 0.0
for line in lines:
    if line[0] != '#': # ignore comments
        words = string.split(line)
        if len(words) == 4:
            coord = float(words[1])
            muProj = float(words[2]) * float(words[3]) / slabVolume
            #print '%f %f ' % (coord, muProj)
            muProjInt = muProjInt + delta * muProj
            elPot = muProjInt * ( e_in_C / A_in_m ) / eps0
            print coord, elPot # [V/m]
    

