#!/usr/bin/env python

# Script: mu2Psi.py
# Author: Mario Orsi (m.orsi at qmul.ac.uk, www.orsi.sems.qmul.ac.uk)
# Purpose: Reads a file containing a dipole projection profile
#          and calculates the corresponding electrostatic potential
# Syntax: python mu2Psi.py inputFile area
# Example: python mu2Psi.py muz.profile 4630 > epp.dat
# Notes: - inputFile = LAMMPS output file generated by fix ave/chunk
#        - area = xy surface area of slabs [Angstrom^2]
# References: - Orsi, Mol. Phys., 112, 1566-1576 (2014)
#             - Orsi & Essex, Faraday Discuss. 161, 249 (2013), eq. 9
#             - Orsi & Essex, PLoS ONE 6, e28637 (2011), p. 15
#             - Sokhan & Tildesley, Mol. Phys. 92, 625 (1997), sec. 3.3

import sys,os,string

if len(sys.argv) != 3:
  print "Syntax: python mu2Psi.py inputFile area"
  sys.exit()

inFileName = sys.argv[1]
A_in_m = 1e-10 # angstrom in meter
area = float(sys.argv[2]) * A_in_m**2
inFile = open(inFileName, "r")
lines = inFile.readlines()
inFile.close()
eps0 = 8.854e-12 # [C/(Vm)] permittivity of free space
e_in_C = 1.6021766e-19 # magnitude of electron charge in Coulomb

# find slab thickness (delta):
for line in lines:
    if line[0] != '#': # ignore comments
        words = string.split(line)
        if len(words) == 3:
            nBins = int(words[1])
        if len(words) == 4:
            if int(words[0]) == 1:
                coordLower = float(words[1])
            if int(words[0]) == nBins:
                coordUpper = float(words[1])
delta = abs( coordUpper - coordLower ) * A_in_m / ( nBins - 1 )
slabVol = area * delta

# calculate & output elec field (file) and elec potential (screen):
outFile = open('Ez.dat', 'w')
EzInt = 0.0 # integral of elec field ( = - elec potential )
for line in lines:
    if line[0] != '#': # ignore comments
        words = string.split(line)
        if len(words) == 4:
            coord = float(words[1])
            muProj = float(words[2])*float(words[3])*e_in_C*A_in_m/slabVol
            Ez = - muProj / eps0
            outFile.write('%f %f\n' % (coord, Ez)) # [A, V/m]
            EzInt = EzInt + delta * Ez
            Psi = - EzInt # elec potential
            print coord, Psi # [A, V]
outFile.close()
    

