#!/usr/bin/env python

# Script: numDens2massDens.py
# Author: Mario Orsi
# Purpose: This script processes a file containing a number density
#          distribution generated by 'fix ave/spatial'
# Syntax: numDens2massDens.py inputFile atomMass
#         inputFile = LAMMPS output file generated by fix ave/spatial
#         atomMass = atomic mass in g/mol or a.m.u.
# Example: python numDens2massDens.py numDensO.zProfile 16.0 > massDensO.dat
# Notes: output is in units of g/cm^3
# Reference: Orsi 2014, Mol. Phys., 112, 1566-1576 (Supplemental)     

import sys,os,string

if len(sys.argv) != 3:
  print "Syntax: python numDens2massDens.py inputFile atomMass"
  sys.exit()

inFileName = sys.argv[1]
inFile = open(inFileName, "r")
lines = inFile.readlines()
inFile.close()

atomMass = float(sys.argv[2])
A3_in_cm3 = 1e-24 # 1 A^3 = 10^-24 cm^3

mol = 6.0221367e23 # number of atoms per mol

# calculate and electron density:
for line in lines:
    if line[0] != '#': # ignore comments
        words = string.split(line)
        if len(words) == 4:
            coord = float(words[1])
            massDensity = float(words[3])*atomMass/(mol*A3_in_cm3)
            print coord, massDensity # [A, g/cm^3]
