#!/usr/bin/env python

# Script:  qDens2Psi.py
# Purpose: This script reads a file containing a charge density profile
#          and calculates the corresponding electrostatic potential (Psi).
# Syntax:  qDens2Psi.py inputFile
#          inputFile = LAMMPS output file generated by fix ave/spatial
# Author:  Mario Orsi (orsimario at gmail.com)

import sys,os,string

if len(sys.argv) != 2:
  print "Syntax: qDens2Psi.py inputFile"
  sys.exit()

inFileName = sys.argv[1]
inFile = open(inFileName, "r")
lines = inFile.readlines()
qDensInt = 0.0

# find bin thickness (delta):
for line in lines:
    if line[0] != '#': # ignore comments
        words = string.split(line)
        if len(words) == 2:
            nBins = int(words[1])
        if len(words) == 4:
            if int(words[0]) == 1:
                coordLower = float(words[1])
            if int(words[0]) == nBins:
                coordUpper = float(words[1])
delta = abs( coordUpper - coordLower ) / ( nBins - 1 )
#print delta

# calculate and output electric field
outFile = open('elecField.dat', 'w')
for line in lines:
    if line[0] != '#': # ignore comments
        words = string.split(line)
        if len(words) == 4:
            coord = float(words[1])
            qDens = float(words[2]) * float(words[3])
            #print '%f %f ' % (coord, qDens)
            qDensInt = qDensInt + delta * qDens
            outFile.write('%f %f\n' % (coord, qDensInt))
            #print '%f %f ' % (coord, qDensInt)



